// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CacheObject.proto

package py.webcache.handler.proto;

public final class CacheObjectProtocol {
  private CacheObjectProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CacheObjectProtoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string key = 1;
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * request info begin 
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * request info begin 
     * </pre>
     */
    String getKey();
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * request info begin 
     * </pre>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    // optional string content = 5;
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     * response info begin 
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     * response info begin 
     * </pre>
     */
    String getContent();
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     * response info begin 
     * </pre>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    // optional string contentType = 6;
    /**
     * <code>optional string contentType = 6;</code>
     */
    boolean hasContentType();
    /**
     * <code>optional string contentType = 6;</code>
     */
    String getContentType();
    /**
     * <code>optional string contentType = 6;</code>
     */
    com.google.protobuf.ByteString
        getContentTypeBytes();

    // optional string characterEncoding = 7;
    /**
     * <code>optional string characterEncoding = 7;</code>
     *
     * <pre>
     * response info end 
     * </pre>
     */
    boolean hasCharacterEncoding();
    /**
     * <code>optional string characterEncoding = 7;</code>
     *
     * <pre>
     * response info end 
     * </pre>
     */
    String getCharacterEncoding();
    /**
     * <code>optional string characterEncoding = 7;</code>
     *
     * <pre>
     * response info end 
     * </pre>
     */
    com.google.protobuf.ByteString
        getCharacterEncodingBytes();

    // optional int64 putTime = 8;
    /**
     * <code>optional int64 putTime = 8;</code>
     *
     * <pre>
     * cache info begin 
     * </pre>
     */
    boolean hasPutTime();
    /**
     * <code>optional int64 putTime = 8;</code>
     *
     * <pre>
     * cache info begin 
     * </pre>
     */
    long getPutTime();

    // optional int32 expiredTime = 9;
    /**
     * <code>optional int32 expiredTime = 9;</code>
     */
    boolean hasExpiredTime();
    /**
     * <code>optional int32 expiredTime = 9;</code>
     */
    int getExpiredTime();

    // optional int32 cost = 10;
    /**
     * <code>optional int32 cost = 10;</code>
     */
    boolean hasCost();
    /**
     * <code>optional int32 cost = 10;</code>
     */
    int getCost();

    // optional int32 left = 11;
    /**
     * <code>optional int32 left = 11;</code>
     *
     * <pre>
     * cache info end 
     * </pre>
     */
    boolean hasLeft();
    /**
     * <code>optional int32 left = 11;</code>
     *
     * <pre>
     * cache info end 
     * </pre>
     */
    int getLeft();
  }
  /**
   * Protobuf type {@code com.xinhuanet.csis.common.webcache.handler.proto.CacheObjectProto}
   */
  public static final class CacheObjectProto extends
      com.google.protobuf.GeneratedMessage
      implements CacheObjectProtoOrBuilder {
    // Use CacheObjectProto.newBuilder() to construct.
    private CacheObjectProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CacheObjectProto(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CacheObjectProto defaultInstance;
    public static CacheObjectProto getDefaultInstance() {
      return defaultInstance;
    }

    public CacheObjectProto getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CacheObjectProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              key_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000002;
              content_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000004;
              contentType_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000008;
              characterEncoding_ = input.readBytes();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000010;
              putTime_ = input.readInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000020;
              expiredTime_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000040;
              cost_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000080;
              left_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CacheObjectProtocol.internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CacheObjectProtocol.internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CacheObjectProto.class, Builder.class);
    }

    public static com.google.protobuf.Parser<CacheObjectProto> PARSER =
        new com.google.protobuf.AbstractParser<CacheObjectProto>() {
      public CacheObjectProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CacheObjectProto(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<CacheObjectProto> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private Object key_;
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * request info begin 
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * request info begin 
     * </pre>
     */
    public String getKey() {
      Object ref = key_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     *
     * <pre>
     * request info begin 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string content = 5;
    public static final int CONTENT_FIELD_NUMBER = 5;
    private Object content_;
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     * response info begin 
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     * response info begin 
     * </pre>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 5;</code>
     *
     * <pre>
     * response info begin 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string contentType = 6;
    public static final int CONTENTTYPE_FIELD_NUMBER = 6;
    private Object contentType_;
    /**
     * <code>optional string contentType = 6;</code>
     */
    public boolean hasContentType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string contentType = 6;</code>
     */
    public String getContentType() {
      Object ref = contentType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          contentType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string contentType = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      Object ref = contentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string characterEncoding = 7;
    public static final int CHARACTERENCODING_FIELD_NUMBER = 7;
    private Object characterEncoding_;
    /**
     * <code>optional string characterEncoding = 7;</code>
     *
     * <pre>
     * response info end 
     * </pre>
     */
    public boolean hasCharacterEncoding() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string characterEncoding = 7;</code>
     *
     * <pre>
     * response info end 
     * </pre>
     */
    public String getCharacterEncoding() {
      Object ref = characterEncoding_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          characterEncoding_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string characterEncoding = 7;</code>
     *
     * <pre>
     * response info end 
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCharacterEncodingBytes() {
      Object ref = characterEncoding_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        characterEncoding_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int64 putTime = 8;
    public static final int PUTTIME_FIELD_NUMBER = 8;
    private long putTime_;
    /**
     * <code>optional int64 putTime = 8;</code>
     *
     * <pre>
     * cache info begin 
     * </pre>
     */
    public boolean hasPutTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 putTime = 8;</code>
     *
     * <pre>
     * cache info begin 
     * </pre>
     */
    public long getPutTime() {
      return putTime_;
    }

    // optional int32 expiredTime = 9;
    public static final int EXPIREDTIME_FIELD_NUMBER = 9;
    private int expiredTime_;
    /**
     * <code>optional int32 expiredTime = 9;</code>
     */
    public boolean hasExpiredTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 expiredTime = 9;</code>
     */
    public int getExpiredTime() {
      return expiredTime_;
    }

    // optional int32 cost = 10;
    public static final int COST_FIELD_NUMBER = 10;
    private int cost_;
    /**
     * <code>optional int32 cost = 10;</code>
     */
    public boolean hasCost() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 cost = 10;</code>
     */
    public int getCost() {
      return cost_;
    }

    // optional int32 left = 11;
    public static final int LEFT_FIELD_NUMBER = 11;
    private int left_;
    /**
     * <code>optional int32 left = 11;</code>
     *
     * <pre>
     * cache info end 
     * </pre>
     */
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 left = 11;</code>
     *
     * <pre>
     * cache info end 
     * </pre>
     */
    public int getLeft() {
      return left_;
    }

    private void initFields() {
      key_ = "";
      content_ = "";
      contentType_ = "";
      characterEncoding_ = "";
      putTime_ = 0L;
      expiredTime_ = 0;
      cost_ = 0;
      left_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(5, getContentBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(6, getContentTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(7, getCharacterEncodingBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(8, putTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(9, expiredTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(10, cost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(11, left_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKeyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getContentBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getContentTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getCharacterEncodingBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, putTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, expiredTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, cost_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, left_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CacheObjectProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CacheObjectProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CacheObjectProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CacheObjectProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CacheObjectProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CacheObjectProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CacheObjectProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CacheObjectProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CacheObjectProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CacheObjectProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CacheObjectProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.xinhuanet.csis.common.webcache.handler.proto.CacheObjectProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements CacheObjectProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CacheObjectProtocol.internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CacheObjectProtocol.internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CacheObjectProto.class, Builder.class);
      }

      // Construct using com.xinhuanet.csis.common.webcache.handler.proto.CacheObjectProtocol.CacheObjectProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        contentType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        characterEncoding_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        putTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        expiredTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        cost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        left_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CacheObjectProtocol.internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_descriptor;
      }

      public CacheObjectProto getDefaultInstanceForType() {
        return CacheObjectProto.getDefaultInstance();
      }

      public CacheObjectProto build() {
        CacheObjectProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CacheObjectProto buildPartial() {
        CacheObjectProto result = new CacheObjectProto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.contentType_ = contentType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.characterEncoding_ = characterEncoding_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.putTime_ = putTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.expiredTime_ = expiredTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.cost_ = cost_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.left_ = left_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CacheObjectProto) {
          return mergeFrom((CacheObjectProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CacheObjectProto other) {
        if (other == CacheObjectProto.getDefaultInstance()) return this;
        if (other.hasKey()) {
          bitField0_ |= 0x00000001;
          key_ = other.key_;
          onChanged();
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000002;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasContentType()) {
          bitField0_ |= 0x00000004;
          contentType_ = other.contentType_;
          onChanged();
        }
        if (other.hasCharacterEncoding()) {
          bitField0_ |= 0x00000008;
          characterEncoding_ = other.characterEncoding_;
          onChanged();
        }
        if (other.hasPutTime()) {
          setPutTime(other.getPutTime());
        }
        if (other.hasExpiredTime()) {
          setExpiredTime(other.getExpiredTime());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        if (other.hasLeft()) {
          setLeft(other.getLeft());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CacheObjectProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CacheObjectProto) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string key = 1;
      private Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * request info begin 
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * request info begin 
       * </pre>
       */
      public String getKey() {
        Object ref = key_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * request info begin 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * request info begin 
       * </pre>
       */
      public Builder setKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * request info begin 
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       *
       * <pre>
       * request info begin 
       * </pre>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }

      // optional string content = 5;
      private Object content_ = "";
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       * response info begin 
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       * response info begin 
       * </pre>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       * response info begin 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       * response info begin 
       * </pre>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       * response info begin 
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 5;</code>
       *
       * <pre>
       * response info begin 
       * </pre>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        content_ = value;
        onChanged();
        return this;
      }

      // optional string contentType = 6;
      private Object contentType_ = "";
      /**
       * <code>optional string contentType = 6;</code>
       */
      public boolean hasContentType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string contentType = 6;</code>
       */
      public String getContentType() {
        Object ref = contentType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          contentType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string contentType = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContentTypeBytes() {
        Object ref = contentType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          contentType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contentType = 6;</code>
       */
      public Builder setContentType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        contentType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentType = 6;</code>
       */
      public Builder clearContentType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        contentType_ = getDefaultInstance().getContentType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contentType = 6;</code>
       */
      public Builder setContentTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        contentType_ = value;
        onChanged();
        return this;
      }

      // optional string characterEncoding = 7;
      private Object characterEncoding_ = "";
      /**
       * <code>optional string characterEncoding = 7;</code>
       *
       * <pre>
       * response info end 
       * </pre>
       */
      public boolean hasCharacterEncoding() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string characterEncoding = 7;</code>
       *
       * <pre>
       * response info end 
       * </pre>
       */
      public String getCharacterEncoding() {
        Object ref = characterEncoding_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          characterEncoding_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string characterEncoding = 7;</code>
       *
       * <pre>
       * response info end 
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCharacterEncodingBytes() {
        Object ref = characterEncoding_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          characterEncoding_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string characterEncoding = 7;</code>
       *
       * <pre>
       * response info end 
       * </pre>
       */
      public Builder setCharacterEncoding(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        characterEncoding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string characterEncoding = 7;</code>
       *
       * <pre>
       * response info end 
       * </pre>
       */
      public Builder clearCharacterEncoding() {
        bitField0_ = (bitField0_ & ~0x00000008);
        characterEncoding_ = getDefaultInstance().getCharacterEncoding();
        onChanged();
        return this;
      }
      /**
       * <code>optional string characterEncoding = 7;</code>
       *
       * <pre>
       * response info end 
       * </pre>
       */
      public Builder setCharacterEncodingBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        characterEncoding_ = value;
        onChanged();
        return this;
      }

      // optional int64 putTime = 8;
      private long putTime_ ;
      /**
       * <code>optional int64 putTime = 8;</code>
       *
       * <pre>
       * cache info begin 
       * </pre>
       */
      public boolean hasPutTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 putTime = 8;</code>
       *
       * <pre>
       * cache info begin 
       * </pre>
       */
      public long getPutTime() {
        return putTime_;
      }
      /**
       * <code>optional int64 putTime = 8;</code>
       *
       * <pre>
       * cache info begin 
       * </pre>
       */
      public Builder setPutTime(long value) {
        bitField0_ |= 0x00000010;
        putTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 putTime = 8;</code>
       *
       * <pre>
       * cache info begin 
       * </pre>
       */
      public Builder clearPutTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        putTime_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 expiredTime = 9;
      private int expiredTime_ ;
      /**
       * <code>optional int32 expiredTime = 9;</code>
       */
      public boolean hasExpiredTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 expiredTime = 9;</code>
       */
      public int getExpiredTime() {
        return expiredTime_;
      }
      /**
       * <code>optional int32 expiredTime = 9;</code>
       */
      public Builder setExpiredTime(int value) {
        bitField0_ |= 0x00000020;
        expiredTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 expiredTime = 9;</code>
       */
      public Builder clearExpiredTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        expiredTime_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cost = 10;
      private int cost_ ;
      /**
       * <code>optional int32 cost = 10;</code>
       */
      public boolean hasCost() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 cost = 10;</code>
       */
      public int getCost() {
        return cost_;
      }
      /**
       * <code>optional int32 cost = 10;</code>
       */
      public Builder setCost(int value) {
        bitField0_ |= 0x00000040;
        cost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cost = 10;</code>
       */
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000040);
        cost_ = 0;
        onChanged();
        return this;
      }

      // optional int32 left = 11;
      private int left_ ;
      /**
       * <code>optional int32 left = 11;</code>
       *
       * <pre>
       * cache info end 
       * </pre>
       */
      public boolean hasLeft() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 left = 11;</code>
       *
       * <pre>
       * cache info end 
       * </pre>
       */
      public int getLeft() {
        return left_;
      }
      /**
       * <code>optional int32 left = 11;</code>
       *
       * <pre>
       * cache info end 
       * </pre>
       */
      public Builder setLeft(int value) {
        bitField0_ |= 0x00000080;
        left_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 left = 11;</code>
       *
       * <pre>
       * cache info end 
       * </pre>
       */
      public Builder clearLeft() {
        bitField0_ = (bitField0_ & ~0x00000080);
        left_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.xinhuanet.csis.common.webcache.handler.proto.CacheObjectProto)
    }

    static {
      defaultInstance = new CacheObjectProto(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.xinhuanet.csis.common.webcache.handler.proto.CacheObjectProto)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021CacheObject.proto\0220com.xinhuanet.csis." +
      "common.webcache.handler.proto\"\242\001\n\020CacheO" +
      "bjectProto\022\013\n\003key\030\001 \001(\t\022\017\n\007content\030\005 \001(\t" +
      "\022\023\n\013contentType\030\006 \001(\t\022\031\n\021characterEncodi" +
      "ng\030\007 \001(\t\022\017\n\007putTime\030\010 \001(\003\022\023\n\013expiredTime" +
      "\030\t \001(\005\022\014\n\004cost\030\n \001(\005\022\014\n\004left\030\013 \001(\005BG\n0co" +
      "m.xinhuanet.csis.common.webcache.handler" +
      ".protoB\023CacheObjectProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinhuanet_csis_common_webcache_handler_proto_CacheObjectProto_descriptor,
              new String[] { "Key", "Content", "ContentType", "CharacterEncoding", "PutTime", "ExpiredTime", "Cost", "Left", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
